name: Build UBI Image

on:
  push:
    tags:
      - '**'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          COMPONENT="${GITHUB_REF_NAME%%/*}"
          VERSION="${GITHUB_REF_NAME#*/}"
          echo "COMPONENT=$COMPONENT" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          context: ${{ env.COMPONENT }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.COMPONENT }}:${{ env.VERSION }}
